name: tz_datetime_web
description: "Time zoned datetime for tz_datetime package. Web implementation."
version: 1.0.0
repository: https://github.com/llfbandit/tz_datetime/tree/master/tz_datetime_web

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  web: ^1.0.0
  tz_datetime_platform_interface: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
