name: tz_datetime
description: "A Dart package for handling time zoned datetime using native platform implementations"
version: 1.1.0
repository: https://github.com/llfbandit/tz_datetime/tree/master/tz_datetime

topics: 
  - timezone
  - iana
  - date
  - datetime

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  tz_datetime_platform_interface: ^1.1.0
  tz_datetime_android: ^1.1.0
  tz_datetime_darwin: ^1.1.0
  tz_datetime_linux: ^1.1.0
  tz_datetime_web: ^1.1.0
  tz_datetime_windows: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.0.0
