name: tz_datetime_platform_interface
description: A common interface for the tz_datetime package to call dedicated platform methods.
version: 1.0.0
repository: https://github.com/llfbandit/tz_datetime

resolution: workspace

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^6.0.0
