// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Copyright (c) 2026, the tz_datetime project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.llfbandit.tz_datetime.TzDatetime`
class TzDatetime extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<TzDatetime> $type;

  @jni$_.internal
  TzDatetime.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'com/llfbandit/tz_datetime/TzDatetime');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<TzDatetime?> nullableType =
      $TzDatetime$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<TzDatetime> type = $TzDatetime$Type$();
  static final _id_getAvailableTimezones = _class.staticMethodId(
    r'getAvailableTimezones',
    r'()[Ljava/lang/String;',
  );

  static final _getAvailableTimezones = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `static public java.lang.String[] getAvailableTimezones()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<jni$_.JString?>? getAvailableTimezones() {
    return _getAvailableTimezones(_class.reference.pointer,
            _id_getAvailableTimezones as jni$_.JMethodIDPtr)
        .object<jni$_.JArray<jni$_.JString?>?>(
            const jni$_.$JArray$NullableType$<jni$_.JString?>(
                jni$_.$JString$NullableType$()));
  }

  static final _id_getOffset = _class.staticMethodId(
    r'getOffset',
    r'(Ljava/lang/String;J)I',
  );

  static final _getOffset = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int64)>)>>(
          'globalEnv_CallStaticIntMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>, int)>();

  /// from: `static public int getOffset(java.lang.String zone, long utcDate)`
  static int getOffset(
    jni$_.JString? zone,
    int utcDate,
  ) {
    final _$zone = zone?.reference ?? jni$_.jNullReference;
    return _getOffset(_class.reference.pointer,
            _id_getOffset as jni$_.JMethodIDPtr, _$zone.pointer, utcDate)
        .integer;
  }
}

final class $TzDatetime$NullableType$ extends jni$_.JType<TzDatetime?> {
  @jni$_.internal
  const $TzDatetime$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/llfbandit/tz_datetime/TzDatetime;';

  @jni$_.internal
  @core$_.override
  TzDatetime? fromReference(jni$_.JReference reference) => reference.isNull
      ? null
      : TzDatetime.fromReference(
          reference,
        );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<TzDatetime?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($TzDatetime$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($TzDatetime$NullableType$) &&
        other is $TzDatetime$NullableType$;
  }
}

final class $TzDatetime$Type$ extends jni$_.JType<TzDatetime> {
  @jni$_.internal
  const $TzDatetime$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/llfbandit/tz_datetime/TzDatetime;';

  @jni$_.internal
  @core$_.override
  TzDatetime fromReference(jni$_.JReference reference) =>
      TzDatetime.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<TzDatetime?> get nullableType =>
      const $TzDatetime$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($TzDatetime$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($TzDatetime$Type$) &&
        other is $TzDatetime$Type$;
  }
}
