// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

late final _class_NSTimeZone = objc.getClass("NSTimeZone");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_secondsFromGMTForDate_ = objc.registerName(
  "secondsFromGMTForDate:",
);
final _objc_msgSend_1r6ymhb = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_timeZoneWithName_ = objc.registerName("timeZoneWithName:");
final _objc_msgSend_1sotr3r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_systemTimeZone = objc.registerName("systemTimeZone");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_resetSystemTimeZone = objc.registerName("resetSystemTimeZone");
final _objc_msgSend_1pl9qdv = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_defaultTimeZone = objc.registerName("defaultTimeZone");
late final _sel_setDefaultTimeZone_ = objc.registerName("setDefaultTimeZone:");
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_localTimeZone = objc.registerName("localTimeZone");
late final _sel_knownTimeZoneNames = objc.registerName("knownTimeZoneNames");
late final _sel_abbreviationDictionary = objc.registerName(
  "abbreviationDictionary",
);
late final _sel_setAbbreviationDictionary_ = objc.registerName(
  "setAbbreviationDictionary:",
);
late final _sel_timeZoneDataVersion = objc.registerName("timeZoneDataVersion");
late final _sel_secondsFromGMT = objc.registerName("secondsFromGMT");
final _objc_msgSend_1hz7y9r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_abbreviation = objc.registerName("abbreviation");
late final _sel_isDaylightSavingTime = objc.registerName(
  "isDaylightSavingTime",
);
final _objc_msgSend_91o635 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_daylightSavingTimeOffset = objc.registerName(
  "daylightSavingTimeOffset",
);
final _objc_msgSend_1ukqyt8 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1ukqyt8Fpret = objc.msgSendFpretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_nextDaylightSavingTimeTransition = objc.registerName(
  "nextDaylightSavingTimeTransition",
);
late final _sel_description = objc.registerName("description");
late final _sel_isEqualToTimeZone_ = objc.registerName("isEqualToTimeZone:");

enum NSTimeZoneNameStyle {
  NSTimeZoneNameStyleStandard(0),
  NSTimeZoneNameStyleShortStandard(1),
  NSTimeZoneNameStyleDaylightSaving(2),
  NSTimeZoneNameStyleShortDaylightSaving(3),
  NSTimeZoneNameStyleGeneric(4),
  NSTimeZoneNameStyleShortGeneric(5);

  final int value;
  const NSTimeZoneNameStyle(this.value);

  static NSTimeZoneNameStyle fromValue(int value) => switch (value) {
    0 => NSTimeZoneNameStyleStandard,
    1 => NSTimeZoneNameStyleShortStandard,
    2 => NSTimeZoneNameStyleDaylightSaving,
    3 => NSTimeZoneNameStyleShortDaylightSaving,
    4 => NSTimeZoneNameStyleGeneric,
    5 => NSTimeZoneNameStyleShortGeneric,
    _ => throw ArgumentError('Unknown value for NSTimeZoneNameStyle: $value'),
  };
}

late final _sel_localizedName_locale_ = objc.registerName(
  "localizedName:locale:",
);
final _objc_msgSend_1xmmt6t = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();

/// NSExtendedTimeZone
extension NSExtendedTimeZone on NSTimeZone {
  /// abbreviation
  objc.NSString? get abbreviation {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_abbreviation);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// daylightSavingTimeOffset
  double get daylightSavingTimeOffset {
    objc.checkOsVersionInternal(
      'NSTimeZone.daylightSavingTimeOffset',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 5, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(
            object$.ref.pointer,
            _sel_daylightSavingTimeOffset,
          )
        : _objc_msgSend_1ukqyt8(
            object$.ref.pointer,
            _sel_daylightSavingTimeOffset,
          );
  }

  /// description
  objc.NSString get description$1 {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_description);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// isDaylightSavingTime
  bool get isDaylightSavingTime {
    return _objc_msgSend_91o635(object$.ref.pointer, _sel_isDaylightSavingTime);
  }

  /// isEqualToTimeZone:
  bool isEqualToTimeZone(NSTimeZone aTimeZone) {
    return _objc_msgSend_19nvye5(
      object$.ref.pointer,
      _sel_isEqualToTimeZone_,
      aTimeZone.ref.pointer,
    );
  }

  /// localizedName:locale:
  objc.NSString? localizedName(
    NSTimeZoneNameStyle style, {
    objc.NSLocale? locale,
  }) {
    objc.checkOsVersionInternal(
      'NSTimeZone.localizedName:locale:',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 5, 0)),
    );
    final $ret = _objc_msgSend_1xmmt6t(
      object$.ref.pointer,
      _sel_localizedName_locale_,
      style.value,
      locale?.ref.pointer ?? ffi.nullptr,
    );
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// nextDaylightSavingTimeTransition
  objc.NSDate? get nextDaylightSavingTimeTransition {
    objc.checkOsVersionInternal(
      'NSTimeZone.nextDaylightSavingTimeTransition',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 5, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_nextDaylightSavingTimeTransition,
    );
    return $ret.address == 0
        ? null
        : objc.NSDate.fromPointer($ret, retain: true, release: true);
  }

  /// secondsFromGMT
  int get secondsFromGMT {
    return _objc_msgSend_1hz7y9r(object$.ref.pointer, _sel_secondsFromGMT);
  }

  /// abbreviationDictionary
  static objc.NSDictionary getAbbreviationDictionary() {
    objc.checkOsVersionInternal(
      'NSTimeZone.abbreviationDictionary',
      iOS: (false, (4, 0, 0)),
      macOS: (false, (10, 6, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSTimeZone,
      _sel_abbreviationDictionary,
    );
    return objc.NSDictionary.fromPointer($ret, retain: true, release: true);
  }

  /// defaultTimeZone
  static NSTimeZone getDefaultTimeZone() {
    final $ret = _objc_msgSend_151sglz(_class_NSTimeZone, _sel_defaultTimeZone);
    return NSTimeZone.fromPointer($ret, retain: true, release: true);
  }

  /// knownTimeZoneNames
  static objc.NSArray getKnownTimeZoneNames() {
    final $ret = _objc_msgSend_151sglz(
      _class_NSTimeZone,
      _sel_knownTimeZoneNames,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  /// localTimeZone
  static NSTimeZone getLocalTimeZone() {
    final $ret = _objc_msgSend_151sglz(_class_NSTimeZone, _sel_localTimeZone);
    return NSTimeZone.fromPointer($ret, retain: true, release: true);
  }

  /// resetSystemTimeZone
  static void resetSystemTimeZone() {
    _objc_msgSend_1pl9qdv(_class_NSTimeZone, _sel_resetSystemTimeZone);
  }

  /// setAbbreviationDictionary:
  static void setAbbreviationDictionary(objc.NSDictionary value) {
    objc.checkOsVersionInternal(
      'NSTimeZone.setAbbreviationDictionary:',
      iOS: (false, (4, 0, 0)),
      macOS: (false, (10, 6, 0)),
    );
    _objc_msgSend_xtuoz7(
      _class_NSTimeZone,
      _sel_setAbbreviationDictionary_,
      value.ref.pointer,
    );
  }

  /// setDefaultTimeZone:
  static void setDefaultTimeZone(NSTimeZone value) {
    _objc_msgSend_xtuoz7(
      _class_NSTimeZone,
      _sel_setDefaultTimeZone_,
      value.ref.pointer,
    );
  }

  /// systemTimeZone
  static NSTimeZone getSystemTimeZone() {
    final $ret = _objc_msgSend_151sglz(_class_NSTimeZone, _sel_systemTimeZone);
    return NSTimeZone.fromPointer($ret, retain: true, release: true);
  }

  /// timeZoneDataVersion
  static objc.NSString getTimeZoneDataVersion() {
    objc.checkOsVersionInternal(
      'NSTimeZone.timeZoneDataVersion',
      iOS: (false, (4, 0, 0)),
      macOS: (false, (10, 6, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSTimeZone,
      _sel_timeZoneDataVersion,
    );
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

/// NSTimeZoneCreation
extension NSTimeZoneCreation on NSTimeZone {}

/// NSTimeZone
extension type NSTimeZone._(objc.ObjCObject object$)
    implements
        objc.ObjCObject,
        objc.NSObject,
        objc.NSCopying,
        objc.NSSecureCoding {
  /// Constructs a [NSTimeZone] that points to the same underlying object as [other].
  NSTimeZone.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [NSTimeZone] that wraps the given raw object pointer.
  NSTimeZone.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [NSTimeZone].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_NSTimeZone,
  );

  /// timeZoneWithName:
  static NSTimeZone? timeZoneWithName(objc.NSString tzName) {
    final $ret = _objc_msgSend_1sotr3r(
      _class_NSTimeZone,
      _sel_timeZoneWithName_,
      tzName.ref.pointer,
    );
    return $ret.address == 0
        ? null
        : NSTimeZone.fromPointer($ret, retain: true, release: true);
  }
}

extension NSTimeZone$Methods on NSTimeZone {
  /// secondsFromGMTForDate:
  int secondsFromGMTForDate(objc.NSDate aDate) {
    return _objc_msgSend_1r6ymhb(
      object$.ref.pointer,
      _sel_secondsFromGMTForDate_,
      aDate.ref.pointer,
    );
  }
}
