name: tz_datetime_linux_example
description: "Demonstrates how to use the tz_datetime plugin."
publish_to: 'none'

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  tz_datetime_linux: any

dev_dependencies:
  lints: ^6.0.0
